package gov.cdc.izgw.v2tofhir.utils;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * ISO-3166 tables and country lookup.
 * @author Audacious Inquiry
 *
 */
public class ISO3166 {
	private ISO3166() {}
	private static final String[][] data = {
		{ 	"AD", "AND", "Andorra" },
		{ 	"AE", "ARE", "United Arab Emirates" },
		{ 	"AF", "AFG", "Afghanistan" },
		{ 	"AI", "AIA", "Anguilla" },
		{ 	"AL", "ALB", "Albania" },
		{ 	"AM", "ARM", "Armenia" },
		{ 	"AO", "AGO", "Angola" },
		{ 	"AQ", "ATA", "Antarctica" },
		{ 	"AR", "ARG", "Argentina" },
		{ 	"AS", "ASM", "American Samoa" },
		{ 	"AT", "AUT", "Austria" },
		{ 	"AU", "AUS", "Australia" },
		{ 	"AW", "ABW", "Aruba" },
		{ 	"AX", "ALA", "Eland Islands" },
		{ 	"AZ", "AZE", "Azerbaijan" },
		{ 	"BB", "BRB", "Barbados" },
		{ 	"BD", "BGD", "Bangladesh" },
		{ 	"BE", "BEL", "Belgium" },
		{ 	"BF", "BFA", "Burkina Faso" },
		{ 	"BG", "BGR", "Bulgaria" },
		{ 	"BH", "BHR", "Bahrain" },
		{ 	"BI", "BDI", "Burundi" },
		{ 	"BJ", "BEN", "Benin" },
		{ 	"BL", "BLM", "Saint Barthilemy" },
		{ 	"BM", "BMU", "Bermuda" },
		{ 	"BN", "BRN", "Brunei Darussalam" },
		{ 	"BO", "BOL", "Bolivia", "Plurinational State Bolivia" },
		{ 	"BR", "BRA", "Brazil" },
		{ 	"BS", "BHS", "Bahamas" },
		{ 	"BT", "BTN", "Bhutan" },
		{ 	"BV", "BVT", "Bouvet Island" },
		{ 	"BW", "BWA", "Botswana" },
		{ 	"BY", "BLR", "Belarus" },
		{ 	"BZ", "BLZ", "Belize" },
		{ 	"CA", "CAN", "Canada" },
		{ 	"CC", "CCK", "Cocos Islands", "Keeling Islands" },
		{ 	"CD", "COD", "Congo", "Democratic Republic Congo" },
		{ 	"CF", "CAF", "Central African Republic" },
		{ 	"CG", "COG", "Congo" },
		{ 	"CH", "CHE", "Switzerland" },
		{ 	"CI", "CIV", "Ctte d'Ivoire" },
		{ 	"CK", "COK", "Cook Islands" },
		{ 	"CL", "CHL", "Chile" },
		{ 	"CM", "CMR", "Cameroon" },
		{ 	"CN", "CHN", "China" },
		{ 	"CO", "COL", "Colombia" },
		{ 	"CR", "CRI", "Costa Rica" },
		{ 	"CU", "CUB", "Cuba" },
		{ 	"CV", "CPV", "Cabo Verde" },
		{ 	"CW", "CUW", "Curagao" },
		{ 	"CX", "CXR", "Christmas Island" },
		{ 	"CY", "CYP", "Cyprus" },
		{ 	"CZ", "CZE", "Czechia" },
		{ 	"DE", "DEU", "Germany" },
		{ 	"DJ", "DJI", "Djibouti" },
		{ 	"DK", "DNK", "Denmark" },
		{ 	"DM", "DMA", "Dominica" },
		{ 	"DO", "DOM", "Dominican Republic" },
		{ 	"DZ", "DZA", "Algeria" },
		{ 	"EC", "ECU", "Ecuador" },
		{ 	"EE", "EST", "Estonia" },
		{ 	"EG", "EGY", "Egypt" },
		{ 	"EH", "ESH", "Western Sahara" },
		{ 	"ER", "ERI", "Eritrea" },
		{ 	"ES", "ESP", "Spain" },
		{ 	"ET", "ETH", "Ethiopia" },
		{ 	"FI", "FIN", "Finland" },
		{ 	"FJ", "FJI", "Fiji" },
		{ 	"FK", "FLK", "Falkland Islands", "Malvinas" },
		{ 	"FM", "FSM", "Micronesia", "Federated States Micronesia" },
		{ 	"FO", "FRO", "Faroe Islands" },
		{ 	"FR", "FRA", "France" },
		{ 	"GA", "GAB", "Gabon" },
		{ 	"GD", "GRD", "Grenada" },
		{ 	"GE", "GEO", "Georgia" },
		{ 	"GF", "GUF", "French Guiana" },
		{ 	"GG", "GGY", "Guernsey" },
		{ 	"GH", "GHA", "Ghana" },
		{ 	"GI", "GIB", "Gibraltar" },
		{ 	"GL", "GRL", "Greenland" },
		{ 	"GM", "GMB", "Gambia" },
		{ 	"GN", "GIN", "Guinea" },
		{ 	"GP", "GLP", "Guadeloupe" },
		{ 	"GQ", "GNQ", "Equatorial Guinea" },
		{ 	"GR", "GRC", "Greece" },
		{ 	"GT", "GTM", "Guatemala" },
		{ 	"GU", "GUM", "Guam" },
		{ 	"GW", "GNB", "Guinea-Bissau" },
		{ 	"GY", "GUY", "Guyana" },
		{ 	"HK", "HKG", "Hong Kong" },
		{ 	"HN", "HND", "Honduras" },
		{ 	"HR", "HRV", "Croatia" },
		{ 	"HT", "HTI", "Haiti" },
		{ 	"HU", "HUN", "Hungary" },
		{ 	"ID", "IDN", "Indonesia" },
		{ 	"IE", "IRL", "Ireland" },
		{ 	"IL", "ISR", "Israel" },
		{ 	"IM", "IMN", "Isle Man" },
		{ 	"IN", "IND", "India" },
		{ 	"IO", "IOT", "British Indian Ocean Territory" },
		{ 	"IQ", "IRQ", "Iraq" },
		{ 	"IR", "IRN", "Iran", "Islamic Republic Iran" },
		{ 	"IS", "ISL", "Iceland" },
		{ 	"IT", "ITA", "Italy" },
		{ 	"JE", "JEY", "Jersey" },
		{ 	"JM", "JAM", "Jamaica" },
		{ 	"JO", "JOR", "Jordan" },
		{ 	"JP", "JPN", "Japan" },
		{ 	"KE", "KEN", "Kenya" },
		{ 	"KG", "KGZ", "Kyrgyzstan" },
		{ 	"KH", "KHM", "Cambodia" },
		{ 	"KI", "KIR", "Kiribati" },
		{ 	"KM", "COM", "Comoros" },
		{ 	"KP", "PRK", "Korea", "Democratic People's Republic Korea" },
		{ 	"KR", "KOR", "Korea", "Republic Korea" },
		{ 	"KW", "KWT", "Kuwait" },
		{ 	"KY", "CYM", "Cayman Islands" },
		{ 	"KZ", "KAZ", "Kazakhstan" },
		{ 	"LA", "LAO", "Lao People's Democratic Republic" },
		{ 	"LB", "LBN", "Lebanon" },
		{ 	"LC", "LCA", "Saint Lucia" },
		{ 	"LI", "LIE", "Liechtenstein" },
		{ 	"LK", "LKA", "Sri Lanka" },
		{ 	"LR", "LBR", "Liberia" },
		{ 	"LS", "LSO", "Lesotho" },
		{ 	"LT", "LTU", "Lithuania" },
		{ 	"LU", "LUX", "Luxembourg" },
		{ 	"LV", "LVA", "Latvia" },
		{ 	"LY", "LBY", "Libya" },
		{ 	"MA", "MAR", "Morocco" },
		{ 	"MC", "MCO", "Monaco" },
		{ 	"MD", "MDA", "Moldova", "Republic Moldova" },
		{ 	"ME", "MNE", "Montenegro" },
		{ 	"MF", "MAF", "Saint Martin" },
		{ 	"MG", "MDG", "Madagascar" },
		{ 	"MH", "MHL", "Marshall Islands" },
		{ 	"MK", "MKD", "Macedonia", "Yugoslav Republic Macedonia" },
		{ 	"ML", "MLI", "Mali" },
		{ 	"MM", "MMR", "Myanmar" },
		{ 	"MN", "MNG", "Mongolia" },
		{ 	"MO", "MAC", "Macao" },
		{ 	"MP", "MNP", "Northern Mariana Islands" },
		{ 	"MQ", "MTQ", "Martinique" },
		{ 	"MR", "MRT", "Mauritania" },
		{ 	"MS", "MSR", "Montserrat" },
		{ 	"MT", "MLT", "Malta" },
		{ 	"MU", "MUS", "Mauritius" },
		{ 	"MV", "MDV", "Maldives" },
		{ 	"MW", "MWI", "Malawi" },
		{ 	"MX", "MEX", "Mexico" },
		{ 	"MY", "MYS", "Malaysia" },
		{ 	"MZ", "MOZ", "Mozambique" },
		{ 	"NA", "NAM", "Namibia" },
		{ 	"NC", "NCL", "New Caledonia" },
		{ 	"NE", "NER", "Niger" },
		{ 	"NF", "NFK", "Norfolk Island" },
		{ 	"NG", "NGA", "Nigeria" },
		{ 	"NI", "NIC", "Nicaragua" },
		{ 	"NL", "NLD", "Netherlands" },
		{ 	"NO", "NOR", "Norway" },
		{ 	"NP", "NPL", "Nepal" },
		{ 	"NR", "NRU", "Nauru" },
		{ 	"NU", "NIU", "Niue" },
		{ 	"NZ", "NZL", "New Zealand" },
		{ 	"OM", "OMN", "Oman" },
		{ 	"PA", "PAN", "Panama" },
		{ 	"PE", "PER", "Peru" },
		{ 	"PF", "PYF", "French Polynesia" },
		{ 	"PG", "PNG", "Papua New Guinea" },
		{ 	"PH", "PHL", "Philippines" },
		{ 	"PK", "PAK", "Pakistan" },
		{ 	"PL", "POL", "Poland" },
		{ 	"PN", "PCN", "Pitcairn" },
		{ 	"PR", "PRI", "Puerto Rico" },
		{ 	"PS", "PSE", "Palestine", "State Palestine" },
		{ 	"PT", "PRT", "Portugal" },
		{ 	"PW", "PLW", "Palau" },
		{ 	"PY", "PRY", "Paraguay" },
		{ 	"QA", "QAT", "Qatar" },
		{ 	"RE", "REU", "Riunion" },
		{ 	"RO", "ROU", "Romania" },
		{ 	"RS", "SRB", "Serbia" },
		{ 	"RU", "RUS", "Russian Federation" },
		{ 	"RW", "RWA", "Rwanda" },
		{ 	"SA", "SAU", "Saudi Arabia" },
		{ 	"SB", "SLB", "Solomon Islands" },
		{ 	"SC", "SYC", "Seychelles" },
		{ 	"SD", "SDN", "Sudan" },
		{ 	"SE", "SWE", "Sweden" },
		{ 	"SG", "SGP", "Singapore" },
		{ 	"SI", "SVN", "Slovenia" },
		{ 	"SK", "SVK", "Slovakia" },
		{ 	"SL", "SLE", "Sierra Leone" },
		{ 	"SM", "SMR", "San Marino" },
		{ 	"SN", "SEN", "Senegal" },
		{ 	"SO", "SOM", "Somalia" },
		{ 	"SR", "SUR", "Suriname" },
		{ 	"SS", "SSD", "South Sudan" },
		{ 	"SV", "SLV", "El Salvador" },
		{ 	"SX", "SXM", "Sint Maarten" },
		{ 	"SY", "SYR", "Syrian Arab Republic" },
		{ 	"SZ", "SWZ", "Swaziland" },
		{ 	"TD", "TCD", "Chad" },
		{ 	"TF", "ATF", "French Southern Territories" },
		{ 	"TG", "TGO", "Togo" },
		{ 	"TH", "THA", "Thailand" },
		{ 	"TJ", "TJK", "Tajikistan" },
		{ 	"TK", "TKL", "Tokelau" },
		{ 	"TL", "TLS", "Timor-Leste" },
		{ 	"TM", "TKM", "Turkmenistan" },
		{ 	"TN", "TUN", "Tunisia" },
		{ 	"TO", "TON", "Tonga" },
		{ 	"TR", "TUR", "Turkey" },
		{ 	"TV", "TUV", "Tuvalu" },
		{ 	"TW", "TWN", "Taiwan", "Province China Taiwan" },
		{ 	"TZ", "TZA", "Tanzania", "United Republic Tanzania" },
		{ 	"UA", "UKR", "Ukraine" },
		{ 	"UG", "UGA", "Uganda" },
		{ 	"UM", "UMI", "United States Minor Outlying Islands" },
		{ 	"US", "USA", "United States America", "United States", "America" },
		{ 	"UY", "URY", "Uruguay" },
		{ 	"UZ", "UZB", "Uzbekistan" },
		{ 	"VA", "VAT", "Holy See", "Vatican" },
		{ 	"VE", "VEN", "Venezuela", "Bolivarian Republic Venezuela" },
		{ 	"VG", "VGB", "Virgin Islands", "British Virgin Islands" },
		{ 	"VN", "VNM", "Viet Nam", "Vietnam" },
		{ 	"VU", "VUT", "Vanuatu" },
		{ 	"WS", "WSM", "Samoa" },
		{ 	"YE", "YEM", "Yemen" },
		{ 	"YT", "MYT", "Mayotte" },
		{ 	"ZA", "ZAF", "South Africa" },
		{ 	"ZM", "ZMB", "Zambia" },
		{ 	"ZW", "ZWE", "Zimbabwe" },
		{ 	"AG", "ATG", "Antigua and Barbuda", "Antiguia", "Barbuda" },
		{ 	"BA", "BIH", "Bosnia and Herzegovina", "Bosnia", "Herzegovina" },
		{ 	"BQ", "BES", "Bonaire, Sint Eustatius and Saba", "Bonaire", "Sint Eustatius", "Saba" },
		{ 	"GS", "SGS", "South Georgia and South Sandwich Islands", "South Georgia" },
		{ 	"HM", "HMD", "Heard Island and McDonald Islands", "Heard Island" },
		{ 	"KN", "KNA", "Saint Kitts and Nevis", "Saint Kitts" },
		{ 	"PM", "SPM", "Saint Pierre and Miquelon", "Saint Pierre" },
		{ 	"SH", "SHN", "Saint Helena, Ascension and Tristan da Cunha", "Saint Helena", "Ascension", "Tristan da Cunha"},
		{ 	"SJ", "SJM", "Svalbard and Jan Mayen", "Svalbard", "Jan Mayen" },
		{ 	"ST", "STP", "Sao Tome and Principe", "Sao Tome", "Principe" },
		{ 	"TC", "TCA", "Turks and Caicos Islands", "Turks", "Caicos Islands" },
		{ 	"TT", "TTO", "Trinidad and Tobago", "Trinidad", "Tobago" },
		{ 	"VC", "VCT", "Saint Vincent and Grenadines", "Saint Vincent", "Grenadines" },
		{ 	"WF", "WLF", "Wallis and Futuna", "Wallis", "Futuna" }
	};
	private static Map<String, String[]> lookup = new LinkedHashMap<>();
	static {
		for (String[] array: data) {
			for (String name: array) {
				name = normalize(name);
				lookup.put(name, array);
			}
		}
	}
	private static String normalize(String name) {
		return name.replace(" and ", " ").replace(" of ", "").replace("the ", "").replaceAll("', ", "").toUpperCase();
	}
	/**
	 * Get the ISO-3166 two letter code for the given country name or code
	 * @param name	The country name or ISO code
	 * @return	the ISO-3166 two letter code for the given country 
	 */
	public static String twoLetterCode(String name) {
		String[] array = lookup.get(normalize(name));
		return array == null ? null : array[0];
	}
	/**
	 * Get the ISO-3166 three letter code for the given country name or code
	 * @param name	The country name or ISO code
	 * @return	the ISO-3166 three letter code for the given country 
	 */
	public static String threeLetterCode(String name) {
		String[] array = lookup.get(normalize(name));
		return array == null ? null : array[1];
	}
	/**
	 * Get the ISO-3166 name for the given country name or code
	 * @param name	The country name or ISO code
	 * @return	the ISO-3166 contry name for the given country 
	 */
	public static String name(String name) {
		String[] array = lookup.get(normalize(name));
		return array == null ? null : array[2];
	}
}
