package gov.cdc.izgw.v2tofhir.utils;

import java.util.HashMap;
import java.util.LinkedHashMap;

import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.tuple.Pair;
import org.hl7.fhir.r4.model.Coding;

/**
 * Utility class for parsing and converting V2 ANSI, ISO+ or UCUM unit codes
 * 
 * @author Audacious Inquiry
 *
 */
public class Units {
	// See http://hl7.org/fhir/R4/valueset-ucum-common.html and https://motorcycleguy.blogspot.com/search?q=ucum 
	// TODO: Add display name values to this table.
	private static String[][] mapData = {
		{ "(ARB_U)", "[arb'U]"},
		{ "(BDSK_U)", "[bdsk'U]"},
		{ "(BSA)", "{bsa}"},
		{ "(CAL)", "cal"},
		{ "(CFU)", "{cfu}"},
		{ "(DROP)", "[drp]"},
		{ "(KA_U)", "[ka'U]"},
		{ "(KCAL)", "kcal"},
		{ "(KCAL)/(8.HR)", "kcal/(8.h)"},
		{ "(KCAL)/D", "kcal/d"},
		{ "(KCAL)/HR", "kcal/h"},
		{ "(KNK_U)", "[knk'U]"},
		{ "(MCLG_U)", "[mclg'U]"},
		{ "(OD)", "{od}"},
		{ "(PH)", "pH"},
		{ "(PPB)", "[ppb]"},
		{ "(PPM)", "[ppm]"},
		{ "(PPT)", "[pptr]"},
		{ "(PPTH)", "[ppth]"},
		{ "(TH_U)", "[todd'U]"},
		{ "/(ARB_U)", "/[arb'U]"},
		{ "/(HPF)", "[HPF]"},
		{ "/(TOT)", "/{tot}"},
		{ "/IU", "/[iU]"},
		{ "10*3(RBC)", "10*3{rbc}"},
		{ "10.L", "10.L/(min.m2)"},
		{ "10.UN.S/(CM5.M2)", "dyn.s/(cm5.m2)"},
		{ "10.UN.S/CM5", "dyn.s/cm5"},
		{ "CM_H20", "cm[H20]"},
		{ "CM_H20.S/L", "cm[H20].s/L"},
		{ "CM_H20/(S.M)", "cm[H20]/(s.m)"},
		{ "DBA", "dB[SPL]"},
		{ "DM2/S2", "REM"},
		{ "G(CREAT)", "g{creat}"},
		{ "G(HGB)", "g{hgb}"},
		{ "G(TOT_NIT)", "g{tit_nit}"},
		{ "G(TOT_PROT)", "g{tot_prot}"},
		{ "G(WET_TIS)", "g{wet_tis}"},
		{ "G.M/((HB).M2)", "g.m/{hb}m2"},
		{ "G.M/(HB)", "g.m/{hb}"},
		{ "G/(8.HR)", "g/(8.h)"},
		{ "G/(8.KG.HR)", "g/(8.kg.h)"},
		{ "G/(KG.HR)", "g/(kg.h)"},
		{ "G/HR", "g/h"},
		{ "IN", "[in_us]"},
		{ "IN_HG", "[in_i'Hg]"},
		{ "IU", "[iU]"},
		{ "IU/D", "[iU]/d"},
		{ "IU/HR", "[iU]/h"},
		{ "IU/KG", "[iU]/kg"},
		{ "IU/L", "[iU]/L"},
		{ "IU/MIN", "[iU]/min"},
		{ "IU/ML", "[iU]/mL"},
		{ "K/WATT", "K/W"},
		{ "KG(BODY_WT)", "kg{body_wt}"},
		{ "KG/MS", "kg/m2"},
		{ "KH/H", "kg/h"},
		{ "L/(8.HR)", "L/(8.h)"},
		{ "L/HR", "L/h"},
		{ "LB", "[lb_av]"},
		{ "M/S", "ms/s"},
		{ "MAS", "Ms"},
		{ "MEQ/(8.HR)", "meq/(8.h)"},
		{ "MEQ/(8.HR.KG)", "meq/(8.h.kg)"},
		{ "MEQ/(KG.HR)", "meq/(kg.h)"},
		{ "MEQ/HR", "meq/h"},
		{ "MG/(8.HR)", "mg/(8.h)"},
		{ "MG/(8.HR.KG)", "mg/(8.h.kg)"},
		{ "MG/(KG.HR)", "mg/(kg.h)"},
		{ "MG/HR", "mg/h"},
		{ "MIU/ML", "m[iU]/mL"},
		{ "ML/((HB).M2)", "mL/{hb}.m2"},
		{ "ML/(8.HR)", "mL/(8.h)"},
		{ "ML/(8.HR.KG)", "mL/(8.h.kg)"},
		{ "ML/(HB)", "mL/{hb}"},
		{ "ML/(KG.HR)", "mL/(kg.h)"},
		{ "ML/CM_H20", "mL/cm[H20]"},
		{ "ML/HR", "mL/h"},
		{ "MM(HG)", "mm[Hg]"},
		{ "MM/HR", "mm/h"},
		{ "MMOL/(8.HR.KG)", "mmol/(8.h.kg)"},
		{ "MMOL/(8HR)", "mmol/(8.h)"},
		{ "MMOL/(KG.HR)", "mmol/(kg.h)"},
		{ "MMOL/HR", "mmol/h"},
		{ "NG/(8.HR)", "ng/(8.h)"},
		{ "NG/(8.HR.KG)", "ng/(8.h.kg)"},
		{ "NG/(KG.HR)", "ng/(kg.h)"},
		{ "NG/HR", "ng/h"},
		{ "OSMOL", "osm"},
		{ "OSMOL/KG", "osm/kg"},
		{ "OSMOL/L", "osm/L"},
		{ "PA", "pA"},
		{ "PAL", "Pa"},
		{ "SEC", "''"},
		{ "SIE", "S"},
		{ "UG(8HR)", "ug(8.h)"},
		{ "UG/(8.HR.KG)", "ug/(8.h.kg)"},
		{ "UG/(KG.HR)", "ug/(kg.h)"},
		{ "UG/HR", "ug/h"},
		{ "UIU", "u[iU]"},
		{ "BAR", "bar"},
		{ "/KG", "/kg"},
		{ "/L", "/L"},
		{ "/M3", "/m3"},
		{ "/MIN", "/min"},
		{ "/M3", "/m3"},
		{ "/MIN", "/min"},
		{ "/ML", "/mL"},
		{ "1/ML", "1/mL"},
		{ "10*12/L", "10*12/L"},
		{ "10*3/L", "10*3/L"},
		{ "10*3/ML", "10*3/mL"},
		{ "10*3/MM3", "10*3/mm3"},
		{ "10*6/L", "10*6/L"},
		{ "10*6/ML", "10*6/mL"},
		{ "10*6/MM3", "10*6/mm3"},
		{ "10*9/L", "10*9/L"},
		{ "10*9/ML", "10*9/mL"},
		{ "10*9/MM3", "10*9/mm3"},
		{ "10.L/MIN", "10.L/min"},
		{ "A/M", "a/m"},
		{ "G/L", "g/L"},
		{ "BQ", "Bq"},
		{ "CEL", "cel"},
		{ "CM", "Cm"},
		{ "CM2/S", "cm2/s"},
		{ "D", "d"},
		{ "DB", "dB"},
		{ "DEG", "deg"},
		{ "EQ", "eq"},
		{ "EV", "eV"},
		{ "FG", "fg"},
		{ "FL", "fL"},
		{ "FMOL", "fmol"},
		{ "G", "g"},
		{ "G.M", "g.m"},
		{ "G/(KG.D)", "g/(kg.d)"},
		{ "G/(KG.MIN)", "g/(kg.min)"},
		{ "G/D", "g/d"},
		{ "G/DL", "g/dL"},
		{ "G/KG", "g/kg"},
		{ "L.S", "L.s"},
		{ "G/M2", "g/m2"},
		{ "G/MIN", "g/min"},
		{ "GY", "Gy"},
		{ "H", "h"},
		{ "HL", "hL"},
		{ "J/L", "J/L"},
		{ "KAT", "kat"},
		{ "KAT/KG", "kat/kg"},
		{ "KAT/L", "kat/L"},
		{ "KG", "kg"},
		{ "KG.M/S", "kg.m/s"},
		{ "KG/(S.M2)", "kg/(s.m2)"},
		{ "KG/L", "kg/L"},
		{ "KG/M3", "kg/m3"},
		{ "KG/MIN", "kg/min"},
		{ "KG/MOL", "kg/mol"},
		{ "KG/S", "kg/s"},
		{ "KPA", "kPa"},
		{ "KS", "ks"},
		{ "L", "L"},
		{ "MG", "mg"},
		{ "L/(MIN.M2)", "L/(min.m2)"},
		{ "L/D", "L/d"},
		{ "L/KG", "L/kg"},
		{ "L/MIN", "L/min"},
		{ "L/S", "L/s"},
		{ "LM", "lm"},
		{ "M", "m"},
		{ "M/S2", "m/s2"},
		{ "M2", "m2"},
		{ "M2/S", "m2/s"},
		{ "M3/S", "m3/s"},
		{ "MBAR", "mbar"},
		{ "MBAR.S/L", "mbar.s/L"},
		{ "MEQ", "meq"},
		{ "MEQ/(KG.D)", "meq/(kg.d)"},
		{ "MEQ/(KG.MIN)", "meq/(kg.min)"},
		{ "MEQ/D", "meq/d"},
		{ "MEQ/KG", "meq/kg"},
		{ "MEQ/L", "meq/L"},
		{ "MEQ/MIN", "meq/min"},
		{ "MMOL/(KG.D)", "mmol/(kg.d)"},
		{ "MG/(KG.D)", "mg/(kg.d)"},
		{ "MG/(KG.MIN)", "mg/(kg.min)"},
		{ "MG/D", "mg/d"},
		{ "MG/DL", "mg/dL"},
		{ "MG/KG", "mg/kg"},
		{ "MG/L", "mg/L"},
		{ "MG/M2", "mg/m2"},
		{ "MG/M3", "mg/m3"},
		{ "MG/MIN", "mg/min"},
		{ "ML", "mL"},
		{ "ML/(KG.D)", "mL/(kg.d)"},
		{ "ML/(KG.MIN)", "mL/(kg.min)"},
		{ "ML/(MIN.M2)", "mL/(min.m2)"},
		{ "ML/D", "mL/d"},
		{ "ML/KG", "mL/kg"},
		{ "ML/M2", "mL/m2"},
		{ "ML/MBAR", "mL/mbar"},
		{ "ML/MIN", "mL/min"},
		{ "ML/S", "mL/s"},
		{ "MM", "mm"},
		{ "NG/L", "ng/L"},
		{ "MMOL/(KG.MIN)", "mmol/(kg.min)"},
		{ "MMOL/KG", "mmol/kg"},
		{ "MMOL/L", "mmol/L"},
		{ "MMOL/M2", "mmol/m2"},
		{ "MMOL/MIN", "mmol/min"},
		{ "MOL/(KG.S)", "mol/(kg.s)"},
		{ "MOL/KG", "mol/kg"},
		{ "MOL/L", "mol/L"},
		{ "MOL/M3", "mol/m3"},
		{ "MOL/S", "mol/s"},
		{ "MOSM/L", "mosm/L"},
		{ "MS", "ms"},
		{ "MV", "mV"},
		{ "NG", "ng"},
		{ "NG/(KG.D)", "ng/(kg.d)"},
		{ "NG/(KG.MIN)", "ng/(kg.min)"},
		{ "NG/D", "ng/d"},
		{ "NG/KG", "ng/kg"},
		{ "UEQ", "ueq"},
		{ "NG/M2", "ng/m2"},
		{ "NG/MIN", "ng/min"},
		{ "NG/ML", "ng/mL"},
		{ "NG/S", "ng/s"},
		{ "/NL", "/nL" },
		{ "NKAT", "nkat"},
		{ "NM", "nm"},
		{ "NMOL/S", "nmol/s"},
		{ "NS", "ns"},
		{ "OHM", "Ohm"},
		{ "OHM.M", "Ohm.m"},
		{ "PG", "pg"},
		{ "PG/L", "pg/L"},
		{ "PG/ML", "pg/mL"},
		{ "PKAT", "pkat"},
		{ "PM", "pm"},
		{ "PMOL", "pmol"},
		{ "PS", "ps"},
		{ "PT", "pt"},
		{ "SV", "Sv"},
		{ "T", "t"},
		{ "UG", "ug"},
		{ "UG/(KG.D)", "ug/(kg.d)"},
		{ "UG/(KG.MIN)", "ug/(kg.min)"},
		{ "UG/D", "ug/d"},
		{ "UG/DL", "ug/dL"},
		{ "UG/G", "ug/g"},
		{ "UG/KG", "ug/kg"},
		{ "UG/L", "ug/L"},
		{ "UG/M2", "ug/m2"},
		{ "UG/MIN", "ug/min"},
		{ "UKAT", "ukat"},
		{ "UM", "um"},
		{ "UMOL", "umol"},
		{ "UMOL/D", "umol/d"},
		{ "UMOL/L", "umol/L"},
		{ "UMOL/MIN", "umol/min"},
		{ "US", "us"},
		{ "UV", "uV"},
		{ "V", "V"},
		{ "WB", "Wb"},
	};
	
	private static String[][] commonUcumUnits = {
		{ "{IndexValue}", "IndexValue"},
		{ "{InhaledTobaccoUseAmountYears}", "InhaledTobaccoUseAmountYears"},
		{ "{InhaledTobaccoUsePacks}/d", "InhaledTobaccoUsePacks / day"},
		{ "{INR}", "international normalized ratio"},
		{ "{INR'unit}", "INR'unit"},
		{ "{JDF'U}", "Juvenile Diabetes Foundation unit"},
		{ "{JDF'U}/L", "Juvenile Diabetes Foundation unit per liter"},
		{ "{JuvenileDiabetesFound'U}", "JuvenileDiabetesFound'U"},
		{ "{KCT'U}", "kaolin clotting time"},
		{ "{KRONU'U}/L", "Kronus unit per liter"},
		{ "{KRONU'U}/mL", "Kronus unit per milliliter"},
		{ "{lgCopies}/ml", "lgCopies / milliliter"},
		{ "{log_copies}/mL", "log (base 10) copies per milliliter"},
		{ "{log_IU}/mL", "log (base 10) international unit per milliliter"},
		{ "{LymeIndexValue}", "LymeIndexValue"},
		{ "{M.o.M.}", "M.o.M."},
		{ "{M.o.M}", "multiple of the median"},
		{ "{Markers}", "Markers"},
		{ "{minidrp}", "minidrp"},
		{ "{Molecule}/{Platelet}", "Molecule / Platelet"},
		{ "{M-PortionPhospholipids}", "M-PortionPhospholipids"},
		{ "{MPS'U}", "IgM antiphosphatidylserine unit"},
		{ "{MPS'U}/mL", "IgM antiphosphatidylserine unit per milliliter"},
		{ "{MultOfMean}", "MultOfMean"},
		{ "{NonspecificOunce}", "NonspecificOunce"},
		{ "{Number}", "Number"},
		{ "{OD_unit}", "optical density unit"},
		{ "{Once}/d", "Once / day"},
		{ "{OpticalDensity}", "OpticalDensity"},
		{ "{OpticalDensityIndex}", "OpticalDensityIndex"},
		{ "{OpticalDensityRatio}", "OpticalDensityRatio"},
		{ "{P2Y12 Reaction Units}", "P2Y12 Reaction Units"},
		{ "{Package}", "Package"},
		{ "{Packs}/d", "Packs / day"},
		{ "{PackYears}", "PackYears"},
		{ "{Patch}", "Patch"},
		{ "{Percentile}", "Percentile"},
		{ "{Pill}", "Pill"},
		{ "{Pouches}/wk", "Pouches / week"},
		{ "{RadioactiveT3UptakeRatio}", "RadioactiveT3UptakeRatio"},
		{ "{ratio}", "ratio"},
		{ "{RBC}/uL", "red blood cell per microliter"},
		{ "{RecTiter}", "RecTiter"},
		{ "{Relative'U}", "Relative'U"},
		{ "{RelativeViscosity}", "RelativeViscosity"},
		{ "{RPI'U}", "RPI'U"},
		{ "{RubellaVirus}", "RubellaVirus"},
		{ "{SatIndex}", "SatIndex"},
		{ "{Scoop}", "Scoop"},
		{ "{ScoreOf}", "ScoreOf"},
		{ "{shift}", "shift"},
		{ "{spermatozoa}/mL", "spermatozoa per milliliter"},
		{ "{spray}", "spray"},
		{ "{StandardDeviation}", "StandardDeviation"},
		{ "{StandardIgA'U}", "StandardIgA'U"},
		{ "{StandardIgG'U}", "StandardIgG'U"},
		{ "{StandardIgM'U}", "StandardIgM'U"},
		{ "{StdDeviation'U}", "StdDeviation'U"},
		{ "{StimulatingIndex}", "StimulatingIndex"},
		{ "{Streptozyme'U}", "Streptozyme'U"},
		{ "{ThyroxinUptake'U}", "ThyroxinUptake'U"},
		{ "{TIBC'U}", "TIBC'U"},
		{ "{Times}/wk", "Times / week"},
		{ "{Tine'U}", "Tine'U"},
		{ "{titer}", "titer"},
		{ "{ToxoplasmaIndexValue}", "ToxoplasmaIndexValue"},
		{ "{Vial}", "Vial"},
		{ "{Volume}/{Vvolume}", "Volume / Vvolume"},
		{ "{WeeksDays}", "WeeksDays"},
		{ "{WhiteBloodCell}", "WhiteBloodCell"},
		{ "1/d", "one per day"},
		{ "1/min", "one per minute"},
		{ "10*12/L", "trillion per liter"},
		{ "10*3", "Thousand"},
		{ "10*3.{RBC}", "Thousand Red Blood Cells"},
		{ "10*3.U", "Thousand Per * Unit"},
		{ "10*3/L", "Thousand Per Liter"},
		{ "10*3/mL", "Thousand Per MilliLiter"},
		{ "10*3/uL", "Thousands Per MicroLiter"},
		{ "10*3{Copies}/mL", "Thousand Copies Per MilliLiter"},
		{ "10*-3{Polarization'U}", "(the number ten for arbitrary powers ^ -3) Polarization'U"},
		{ "10*5", "OneHundredThousand"},
		{ "10*6", "Million"},
		{ "10*6.[iU]", "MillionInternationalUnit"},
		{ "10*6.eq/mL", "MillionEquivalentsPerMilliLiter"},
		{ "10*6.U", "(the number ten for arbitrary powers ^ 6) * Unit"},
		{ "10*6/{Specimen}", "MillionPerSpecimen"},
		{ "10*6/kg", "million per kilogram"},
		{ "10*6/L", "million per liter"},
		{ "10*6/mL", "million per milliliter"},
		{ "10*6/mm3", "(the number ten for arbitrary powers ^ 6) / (millimeter ^ 3)"},
		{ "10*6/uL", "million per microliter"},
		{ "10*-6{Immunofluorescence'U}", "(the number ten for arbitrary powers ^ -6) Immunofluorescence'U"},
		{ "10*8", "TenToEighth"},
		{ "10*9/L", "billion per liter"},
		{ "10*9/mL", "billion per milliliter"},
		{ "10*9/uL", "billion per microliter"},
		{ "10.L/(min.m2)", "10 liter per minute per square meter"},
		{ "10.L/min", "10 liter per minute"},
		{ "10.uN.s/(cm.m2)", "10 * microNewton * second / centimeter * (meter ^ 2)"},
		{ "10.uN.s/cm", "10 * microNewton * second / centimeter"},
		{ "10.uN.s/cm2", "10 * microNewton * second / (centimeter ^ 2)"},
		{ "a", "year"},
		{ "A/m", "Ampère / meter"},
		{ "att", "technical atmosphere"},
		{ "bar", "bar"},
		{ "Cel", "degree Celsius"},
		{ "cg", "centigram"},
		{ "cL", "centiliter"},
		{ "cm", "centimeter"},
		{ "cm[H2O]", "centimeter of water"},
		{ "cm[H2O]/(s.m)", "centimeter of water column / second * meter"},
		{ "cm[H2O]/L/s", "centimeter of water per liter per second"},
		{ "cm[Hg]", "centimeter of mercury"},
		{ "cm2", "square centimeter"},
		{ "cm2/s", "square centimeter per second"},
		{ "cm3", "cubic centimeter"},
		{ "cP", "centiPoise"},
		{ "cSt", "centiStokes"},
		{ "d", "day"},
		{ "dB", "decibel"},
		{ "deg", "degree"},
		{ "deg/s", "degree per second"},
		{ "dg", "decigram"},
		{ "dL", "deciliter"},
		{ "dm", "decimeter"},
		{ "dm2/s2", "square decimeter per square second"},
		{ "eq", "equivalents"},
		{ "eq/L", "equivalents / liter"},
		{ "eq/mL", "equivalents / milliliter"},
		{ "eq/mmol", "equivalents / millimole"},
		{ "eq/umol", "equivalents / micromole"},
		{ "erg", "erg"},
		{ "eV", "electronvolt"},
		{ "fg", "femtogram"},
		{ "fL", "femtoliter"},
		{ "fL/nL", "femtoliter / nanoliter"},
		{ "fm", "femtometer"},
		{ "fmol", "femtomole"},
		{ "fmol/g", "femtomole per gram"},
		{ "fmol/L", "femtomole per liter"},
		{ "fmol/mg", "femtomole / milligram"},
		{ "fmol/mL", "femtomole / milliliter"},
		{ "g", "gram"},
		{ "g.m", "gram * meter"},
		{ "g.m/({hb}.m2)", "gram * meter / hb * (meter ^ 2)"},
		{ "g.m/{hb}", "gram * meter / hb"},
		{ "g/(100.g)", "gram per 100 gram"},
		{ "g/(12.h)", "gram per 12 hour"},
		{ "g/(24.h)", "gram per 24 hour"},
		{ "g/(3.d)", "gram per 3 days"},
		{ "g/(4.h)", "gram per 4 hour"},
		{ "g/(48.h)", "gram per 48 hour"},
		{ "g/(5.h)", "gram per 5 hour"},
		{ "g/(6.h)", "gram per 6 hour"},
		{ "g/(72.h)", "gram per 72 hour"},
		{ "g/(8.h)", "gram / 8 * hour"},
		{ "g/(8.kg.h)", "gram / 8 * kilogram * hour"},
		{ "g/(kg.h)", "gram / kilogram * hour"},
		{ "g/(kg.min)", "gram / kilogram * minute"},
		{ "g/{TotalWeight}", "gram / TotalWeight"},
		{ "g/d", "gram per day"},
		{ "g/dL", "gram per deciliter"},
		{ "g/g", "gram per gram"},
		{ "g/g{Cre}", "gram / gram Cre"},
		{ "g/g{creat}", "gram / gram creat"},
		{ "g/g{tissue}", "gram per gram of tissue"},
		{ "g/h", "gram per hour"},
		{ "g/h/m2", "gram per hour per square meter"},
		{ "g/kg", "gram per kilogram"},
		{ "g/kg/d", "gram per kilogram per day"},
		{ "g/L", "gram per liter"},
		{ "g/m2", "grams Per Square Meter"},
		{ "g/mg", "gram per milligram"},
		{ "g/min", "gram per minute"},
		{ "g/mL", "gram per milliliter"},
		{ "g/mmol", "gram per millimole"},
		{ "g/mmol{creat}", "gram / millimole creat"},
		{ "g/mol", "gram per mole"},
		{ "GBq", "gigaBecquerel"},
		{ "h", "hour"},
		{ "hL", "hectoliter"},
		{ "Hz", "Hertz"},
		{ "[iU]", "international unit"},
		{ "J", "joule"},
		{ "J/L", "joule per liter"},
		{ "K", "Kelvin"},
		{ "K/W", "Kelvin / Watt"},
		{ "k[IU]/L", "kilo international unit per liter"},
		{ "k[IU]/mL", "kilo international unit per milliliter"},
		{ "kat/kg", "katal / kilogram"},
		{ "kat/L", "katal / liter"},
		{ "kBq", "kiloBecquerel"},
		{ "kcal", "kilocalorie"},
		{ "kcal/(8.h)", "kilocalorie / 8 * hour"},
		{ "kcal/h", "kilocalorie per hour"},
		{ "kg", "kilogram"},
		{ "kg.m/s", "kilogram meter per second"},
		{ "kg/(s.m2)", "kilogram per second per square meter"},
		{ "kg/h", "kilogram per hour"},
		{ "kg/L", "kilogram per liter"},
		{ "kg/m2", "kilogram / (meter ^ 2)"},
		{ "kg/m3", "kilogram / (meter ^ 3)"},
		{ "kg/min", "kilogram / minute"},
		{ "kg/mol", "kilogram per mole"},
		{ "kg/s", "kilogram / second"},
		{ "kL", "kiloliter"},
		{ "km", "kilometer"},
		{ "kPa", "kiloPascal"},
		{ "ks", "kilosecond"},
		{ "kU/g", "kiloenzyme Unit per gram"},
		{ "kU/h", "kiloUnit / hour"},
		{ "kU/L", "kiloenzyme Unit per liter"},
		{ "kU/mL", "kilo enzyme unit per milliliter"},
		{ "L", "liter"},
		{ "L.s2/s", "liter * (second ^ 2) / second"},
		{ "L/(8.h)", "liter per 8 hour"},
		{ "L/(min.m2)", "liter per minute per square meter"},
		{ "L/d", "liter per day"},
		{ "L/h", "liter per hour"},
		{ "L/kg", "liter per kilogram"},
		{ "L/L", "liter per liter"},
		{ "L/min", "liter per minute"},
		{ "L/s", "liter / second"},
		{ "lm/m2", "lumen / (meter ^ 2)"},
		{ "m", "meter"},
		{ "m/s", "meter per second"},
		{ "m/s2", "meter per square second"},
		{ "m[iU]", "milliinternational unit"},
		{ "m[IU]/L", "milli international unit per liter"},
		{ "m[IU]/mL", "milli international unit per milliliter"},
		{ "m2", "square meter"},
		{ "m2/s", "square meter per second"},
		{ "m3/s", "cubic meter per second"},
		{ "mA", "milliAmpère"},
		{ "mbar", "millibar"},
		{ "mbar.s/L", "millibar second per liter"},
		{ "MBq", "megaBecquerel"},
		{ "mCi", "milliCurie"},
		{ "meq", "milliequivalent"},
		{ "meq/(12.h)", "milliequivalent per 12 hour"},
		{ "meq/(2.h)", "milliequivalent per 2 hour"},
		{ "meq/(24.h)", "milliequivalent per 24 hour"},
		{ "meq/(8.h)", "milliequivalent per 8 hour"},
		{ "meq/(8.h.kg)", "milliequivalents / 8 * hour * kilogram"},
		{ "meq/(kg.d)", "milliequivalents / kilogram * day"},
		{ "meq/{Specimen}", "milliequivalents / Specimen"},
		{ "meq/d", "milliequivalent per day"},
		{ "meq/dL", "milliequivalent per deciliter"},
		{ "meq/g", "milliequivalent per gram"},
		{ "meq/g{Cre}", "milliequivalents / gram Cre"},
		{ "meq/h", "milliequivalent per hour"},
		{ "meq/kg", "milliequivalent per kilogram"},
		{ "meq/kg/h", "milliequivalent per kilogram per hour"},
		{ "meq/kg/min", "milliequivalents / kilogram / minute"},
		{ "meq/L", "milliequivalent per liter"},
		{ "meq/m2", "milliequivalent per square meter"},
		{ "meq/min", "milliequivalent per minute"},
		{ "meq/mL", "milliequivalent per milliliter"},
		{ "mg", "milligram"},
		{ "mg/(10.h)", "milligram per 10 hour"},
		{ "mg/(12.h)", "milligram per 12 hour"},
		{ "mg/(18.h)", "milligram per 18 hour"},
		{ "mg/(2.h)", "milligram per 2 hour"},
		{ "mg/(24.h)", "milligram per 24 hour"},
		{ "mg/(72.h)", "milligram per 72 hour"},
		{ "mg/(8.h)", "milligram per 8 hour"},
		{ "mg/(8.h.kg)", "milligram / 8 * hour * kilogram"},
		{ "mg/(kg.h)", "milligram / kilogram * hour"},
		{ "mg/{Hgb}/g", "milligram / Hgb / gram"},
		{ "mg/{Specimen}", "milligram / Specimen"},
		{ "mg/{Tot'Volume}", "milligram / Tot'Volume"},
		{ "mg/{Volume}", "milligram / Volume"},
		{ "mg/d", "milligram per day"},
		{ "mg/d/(173.10*-2.m2)", "milligram / day / 173 * (the number ten for arbitrary powers ^ -2) * (meter ^ 2)"},
		{ "mg/dL", "milligram per deciliter"},
		{ "mg/g", "milligram per gram"},
		{ "mg/g{Cre}", "milligram / gram Cre"},
		{ "mg/g{creat}", "milligram per gram of creatinine"},
		{ "mg/h", "milligram per hour"},
		{ "mg/kg", "milligram per kilogram"},
		{ "mg/kg/(24.h)", "milligram / kilogram / 24 * hour"},
		{ "mg/kg/d", "milligram per kilogram per day"},
		{ "mg/kg/min", "milligram per kilogram per minute"},
		{ "mg/L", "milligram per liter"},
		{ "mg/m2", "milligram per square meter"},
		{ "mg/m3", "milligram per cubic meter"},
		{ "mg/mg", "milligram per milligram"},
		{ "mg/mg{cre}", "milligram / milligram cre"},
		{ "mg/min", "milligram per minute"},
		{ "mg/mL", "milligram per milliliter"},
		{ "mg/mmol", "milligram per millimole"},
		{ "mg/mmol{Cre}", "milligram / millimole Cre"},
		{ "mg/mmol{creat}", "milligram per millimole of creatinine"},
		{ "mg/wk", "milligram per week"},
		{ "mg{Phenylketones}/dL", "milligram Phenylketones / deciliter"},
		{ "min", "minute"},
		{ "mL", "milliliter"},
		{ "mL/({h'b}.m2)", "milliliter / h'b * (meter ^ 2)"},
		{ "mL/(10.h)", "milliliter per 10 hour"},
		{ "mL/(12.h)", "milliliter per 12 hour"},
		{ "mL/(2.h)", "milliliter per 2 hour"},
		{ "mL/(24.h)", "milliliter per 24 hour"},
		{ "mL/(4.h)", "milliliter per 4 hour"},
		{ "mL/(72.h)", "milliliter per 72 hour"},
		{ "mL/(8.h)", "milliliter per 8 hour"},
		{ "mL/(kg.min)", "milliliter / kilogram * minute"},
		{ "mL/[sin_i]", "milliliter per square inch (international)"},
		{ "mL/{h'b}", "MilliLitersPerHeartbeat [SI Volume Units]"},
		{ "mL/cm[H2O]", "milliliter / centimeter of water column"},
		{ "mL/d", "milliliter per day"},
		{ "mL/dL", "milliliter per deciliter"},
		{ "mL/h", "milliliter per hour"},
		{ "mL/kg", "milliliter per kilogram"},
		{ "mL/kg/(8.h)", "milliliter per kilogram per 8 hour"},
		{ "mL/kg/d", "milliliter per kilogram per day"},
		{ "mL/kg/h", "milliliter per kilogram per hour"},
		{ "mL/kg/min", "milliliter per kilogram per minute"},
		{ "mL/L", "milliliter per liter"},
		{ "mL/m2", "milliliter per square meter"},
		{ "mL/mbar", "milliliter per millibar"},
		{ "mL/min", "milliliter per minute"},
		{ "mL/min/(173.10*-2.m2)", "milliliter / minute / 173 * (the number ten for arbitrary powers ^ -2) * (meter ^ 2)"},
		{ "mL/min/{1.73_m2}", "milliliter per minute per 1.73 square meter"},
		{ "mL/min/m2", "milliliter per minute per square meter"},
		{ "mL/mm", "milliliter per millimeter"},
		{ "mL/s", "milliliter per second"},
		{ "mm", "millimeter"},
		{ "mm/h", "millimeter per hour"},
		{ "mm/min", "millimeter per minute"},
		{ "mm[H2O]", "millimeter of water"},
		{ "mm[Hg]", "millimeter of mercury"},
		{ "mm2", "square millimeter"},
		{ "mm3", "cubic millimeter"},
		{ "mmol", "millimole"},
		{ "mmol/(12.h)", "millimole per 12 hour"},
		{ "mmol/(18.h)", "millimole per 18 hour"},
		{ "mmol/(2.h)", "millimole per 2 hour"},
		{ "mmol/(24.h)", "millimole per 24 hour"},
		{ "mmol/(6.h)", "millimole per 6 hour"},
		{ "mmol/(8.h)", "millimole per 8 hour"},
		{ "mmol/(8.h.kg)", "millimole / 8 * hour * kilogram"},
		{ "mmol/{Tot'Volume}", "millimole / Tot'Volume"},
		{ "mmol/d", "millimole per day"},
		{ "mmol/dL", "millimole per deciliter"},
		{ "mmol/g", "millimole per gram"},
		{ "mmol/g{creat}", "millimole per gram of creatinine"},
		{ "mmol/g{hemoglobin}", "millimole per gram of hemoglobin"},
		{ "mmol/h", "millimole per hour"},
		{ "mmol/h/mg{Hb}", "millimole per hour per milligram of hemoglobin"},
		{ "mmol/h/mg{protein}", "millimole per hour per milligram of protein"},
		{ "mmol/kg", "millimole per kilogram"},
		{ "mmol/kg/d", "millimole per kilogram per day"},
		{ "mmol/kg/h", "millimole per kilogram per hour"},
		{ "mmol/kg/min", "millimole per kilogram per minute"},
		{ "mmol/kg{H2O}", "millimole per kilogram of water"},
		{ "mmol/L", "millimole per liter"},
		{ "mmol/L/s", "millimole per liter per second"},
		{ "mmol/m", "millimole / meter"},
		{ "mmol/m2", "millimole per square meter"},
		{ "mmol/min", "millimole per minute"},
		{ "mmol/mmol", "millimole per millimole"},
		{ "mmol/mol", "millimole per mole"},
		{ "mmol/mol{creat}", "millimole per mole of creatinine"},
		{ "mmol/s/L", "millimole per second per liter"},
		{ "mo", "month"},
		{ "mol", "mole"},
		{ "mol/d", "mole per day"},
		{ "mol/kg", "mole per kilogram"},
		{ "mol/kg/s", "mole per kilogram per second"},
		{ "mol/L", "mole per liter"},
		{ "mol/m3", "mole per cubic meter"},
		{ "mol/mL", "mole per milliliter"},
		{ "mol/mol", "mole per mole"},
		{ "mol/mol{creat}", "mole / mole creat"},
		{ "mol/s", "mole per second"},
		{ "mosm", "milliosmole"},
		{ "mosm/kg", "milliosmole per kilogram"},
		{ "mosm/L", "milliosmole per liter"},
		{ "mPa", "millipascal"},
		{ "ms", "millisecond"},
		{ "mU", "millienzyme Unit"},
		{ "mU/g", "millienzyme Unit per gram"},
		{ "mU/g{Hgb}", "milliUnit / gram Hgb"},
		{ "mU/L", "millienzyme Unit per liter"},
		{ "mU/mg", "milliUnit / milligram"},
		{ "mU/mg{Cre}", "milliUnit / milligram Cre"},
		{ "mU/min", "milliUnit / minute"},
		{ "mU/mL", "millienzyme Unit per milliliter"},
		{ "mU/mL/min", "millienzyme Unit per milliliter per minute"},
		{ "mU/mmol{creatinine}", "millienzyme Unit per millimole of creatinine"},
		{ "mU/mmol{RBCs}", "millienzyme Unit per millimole of red blood cells"},
		{ "mV", "milliVolt"},
		{ "N", "Newton"},
		{ "N.cm", "Newton centimeter"},
		{ "N.s", "Newton second"},
		{ "nCi", "nanoCurie"},
		{ "ng", "nanogram"},
		{ "ng/(24.h)", "nanogram per 24 hour"},
		{ "ng/(8.h)", "nanogram per 8 hour"},
		{ "ng/(8.h.kg)", "nanogram / 8 * hour * kilogram"},
		{ "ng/(kg.d)", "nanogram / kilogram * day"},
		{ "ng/(kg.h)", "nanogram / kilogram * hour"},
		{ "ng/(kg.min)", "nanogram / kilogram * minute"},
		{ "ng/10*6", "nanogram per million"},
		{ "ng/d", "nanogram per day"},
		{ "ng/dL", "nanogram per deciliter"},
		{ "ng/dL/h", "nanogram / deciliter / hour"},
		{ "ng/g", "nanogram per gram"},
		{ "ng/g{Cre}", "nanogram / gram Cre"},
		{ "ng/g{creat}", "nanogram per gram of creatinine"},
		{ "ng/h", "nanogram per hour"},
		{ "ng/kg", "nanogram per kilogram"},
		{ "ng/kg/(8.h)", "nanogram per kilogram per 8 hour"},
		{ "ng/kg/h", "nanogram per kilogram per hour"},
		{ "ng/kg/min", "nanogram per kilogram per minute"},
		{ "ng/L", "nanogram per liter"},
		{ "ng/m2", "nanogram per square meter"},
		{ "ng/mg", "nanogram per milligram"},
		{ "ng/mg/h", "nanogram per milligram per hour"},
		{ "ng/mg{Protein}", "nanogram / milligram Protein"},
		{ "ng/min", "nanogram per minute"},
		{ "ng/mL", "nanogram per millliiter"},
		{ "ng/mL/h", "nanogram per milliliter per hour"},
		{ "ng/mL{rbc}", "nanogram / milliliter rbc"},
		{ "ng/s", "nanogram per second"},
		{ "nkat", "nanokatal"},
		{ "nL", "nanoliter"},
		{ "nm", "nanometer"},
		{ "nm/s/L", "nanometer per second per liter"},
		{ "nmol", "nanomole"},
		{ "nmol/(24.h)", "nanomole per 24 hour"},
		{ "nmol/d", "nanomole per day"},
		{ "nmol/dL", "nanomole per deciliter"},
		{ "nmol/g", "nanomole per gram"},
		{ "nmol/g{Cre}", "nanomole / gram Cre"},
		{ "nmol/g{creat}", "nanomole per gram of creatinine"},
		{ "nmol/g{dry_wt}", "nanomole per gram of dry weight"},
		{ "nmol/h/L", "nanomole per hour per liter"},
		{ "nmol/h/mg{protein}", "nanomole per hour per milligram of protein"},
		{ "nmol/h/mL", "nanomole per hour per milliliter"},
		{ "nmol/L", "nanomole per liter"},
		{ "nmol/L/mmol{creat}", "nanomole per liter per millimole of creatinine"},
		{ "nmol/L/s", "nanomole per liter per second"},
		{ "nmol/L{RBCs}", "nanomole per liter of red blood cells"},
		{ "nmol/m/mg{protein}", "nanomole per meter per milligram of protein"},
		{ "nmol/mg", "nanomole per milligram"},
		{ "nmol/mg/h", "nanomole per milligram per hour"},
		{ "nmol/min/mg{hemoglobin}", "nanomole per minute per milligram of hemoglobin"},
		{ "nmol/min/mg{protein}", "nanomole per minute per milligram of protein"},
		{ "nmol/min/mL", "nanomole per minute per milliliter"},
		{ "nmol/mL", "nanomole per milliliter"},
		{ "nmol/mL/h", "nanomole per milliliter per hour"},
		{ "nmol/mL/min", "nanomole per milliliter per minute"},
		{ "nmol/mmol", "nanomole per millimole"},
		{ "nmol/mmol{Cre}", "nanomole / millimole Cre"},
		{ "nmol/mmol{creat}", "nanomole per millimole of creatinine"},
		{ "nmol/mol", "nanomole per mole"},
		{ "nmol/nmol", "nanomole per nanomole"},
		{ "nmol/s", "nanomole per second"},
		{ "nmol/s/L", "nanomole per second per liter"},
		{ "nmol/umol{creat}", "nanomole per micromole of creatinine"},
		{ "ns", "nanosecond"},
		{ "Ohm", "Ohm"},
		{ "osm/kg", "osmole per kilogram"},
		{ "osm/L", "osmole per liter"},
		{ "Pa", "Pascal"},
		{ "pg", "picogram"},
		{ "pg/dL", "picogram per deciliter"},
		{ "pg/L", "picogram per liter"},
		{ "pg/mg", "picogram per milligram"},
		{ "pg/mL", "picogram per milliliter"},
		{ "pg/mm", "picogram per millimeter"},
		{ "pkat", "picokatal"},
		{ "pL", "picoliter"},
		{ "pm", "picometer"},
		{ "pmol", "picomole"},
		{ "pmol/d", "picomole per day"},
		{ "pmol/dL", "picomole per deciliter"},
		{ "pmol/g", "picomole per gram"},
		{ "pmol/h/mg{protein}", "picomole per hour per milligram of protein"},
		{ "pmol/h/mL", "picomole per hour per milliliter"},
		{ "pmol/L", "picomole per liter"},
		{ "pmol/mg{protein}", "picomole per milligram of protein"},
		{ "pmol/min", "picomole per minute"},
		{ "pmol/min/mg{protein}", "picomole per minute per milligram of protein"},
		{ "pmol/mL", "picomole per milliliter"},
		{ "pmol/mmol", "picomole per millimole"},
		{ "pmol/mmol{creat}", "picomole per millimole of creatinine"},
		{ "pmol/mol", "picomole per mole"},
		{ "pmol/umol", "picomole per micromole"},
		{ "pmol/umol{creat}", "picomole per micromole of creatinine"},
		{ "ps", "picosecond"},
		{ "pT", "picotesla"},
		{ "s", "second"},
		{ "St", "Stokes"},
		{ "t", "tonne"},
		{ "U", "enzyme Unit"},
		{ "U/(1.h)", "enzyme Unit per 1 hour"},
		{ "U/(12.h)", "enzyme unit per 12 hour"},
		{ "U/(18.h)", "enzyme Unit per 18 hour"},
		{ "U/(2.h)", "enzyme unit per 2 hour"},
		{ "U/(24.h)", "enzyme unit per 24 hour"},
		{ "U/10*10{cells}", "enzyme unit per 10 billion cells"},
		{ "U/10*12", "enzyme unit per trillion"},
		{ "U/10*6", "enzyme unit per million"},
		{ "U/10*9", "enzyme unit per billion"},
		{ "U/d", "enzyme unit per day"},
		{ "U/dL", "enzyme unit per deciliter"},
		{ "U/g", "enzyme unit per gram"},
		{ "U/g{Cre}", "Unit / gram Cre"},
		{ "U/g{Hb}", "enzyme unit per gram of hemoglobin"},
		{ "U/g{hemoglobin}", "enzyme Unit per gram of hemoglobin"},
		{ "U/g{Hgb}", "UnitsPerGramHemoglobin"},
		{ "U/h", "enzyme unit per hour"},
		{ "U/kg/h", "Unit / kilogram / hour"},
		{ "U/kg{Hb}", "enzyme unit per kilogram of hemoglobin"},
		{ "U/kg{hemoglobin}", "enzyme Unit per kilogram of hemoglobin"},
		{ "U/L", "enzyme unit per liter"},
		{ "U/min", "enzyme unit per minute"},
		{ "U/mL", "enzyme unit per milliliter"},
		{ "U/mL{RBC}", "Unit / milliliter RBC"},
		{ "U/mL{RBCs}", "enzyme unit per milliliter of red blood cells"},
		{ "U/mmol{creat}", "enzyme unit per millimole of creatinine"},
		{ "U/mol", "enzyme Unit per mole"},
		{ "U/s", "enzyme unit per second"},
		{ "U/umol", "enzyme Unit per micromole"},
		{ "u[IU]", "micro international unit"},
		{ "u[IU]/L", "microinternational unit per liter"},
		{ "u[IU]/mL", "micro international unit per milliliter"},
		{ "ueq", "microequivalents"},
		{ "ueq/L", "microequivalent per liter"},
		{ "ueq/mL", "microequivalent per milliliter"},
		{ "ug", "microgram"},
		{ "ug/(24.h)", "microgram per 24 hour"},
		{ "ug/(8.h)", "microgram per 8 hour"},
		{ "ug/(kg.d)", "microgram / kilogram * day"},
		{ "ug/(kg.h)", "microgram / kilogram * hour"},
		{ "ug/{Specimen}", "microgram / Specimen"},
		{ "ug/{TotalVolume}", "MicroGramsPerTotalVolume"},
		{ "ug/d", "microgram per day"},
		{ "ug/dL", "microgram per deciliter"},
		{ "ug/dL{rbc}", "microgram / deciliter rbc"},
		{ "ug/g", "microgram per gram"},
		{ "ug/g{Cre}", "microgram / gram Cre"},
		{ "ug/g{creat}", "microgram per gram of creatinine"},
		{ "ug/g{DryWeight}", "microgram / gram DryWeight"},
		{ "ug/g{Hgb}", "microgram / gram Hgb"},
		{ "ug/g{Tissue}", "microgram / gram Tissue"},
		{ "ug/h", "microgram per hour"},
		{ "ug/kg", "microgram per kilogram"},
		{ "ug/kg/(8.h)", "microgram per kilogram per 8 hour"},
		{ "ug/kg/d", "microgram per kilogram per day"},
		{ "ug/kg/h", "microgram per kilogram per hour"},
		{ "ug/kg/min", "microgram per kilogram per minute"},
		{ "ug/L", "microgram per liter"},
		{ "ug/L/(24.h)", "microgram per liter per 24 hour"},
		{ "ug/L{DDU}", "microgram / liter DDU"},
		{ "ug/m2", "microgram per square meter"},
		{ "ug/mg", "microgram per milligram"},
		{ "ug/mg{Cre}", "microgram / milligram Cre"},
		{ "ug/mg{creat}", "microgram per milligram of creatinine"},
		{ "ug/min", "microgram per minute"},
		{ "ug/mL", "microgram per milliliter"},
		{ "ug/mL{FEU}", "microgram / milliliter FEU"},
		{ "ug/mmol", "microgram per millimole"},
		{ "ug/ng", "microgram per nanogram"},
		{ "ug{T4}/dL", "microgram T4 / deciliter"},
		{ "ukat", "microkatal"},
		{ "uL", "microliter"},
		{ "uL/(2.h)", "microliter per 2 hour"},
		{ "uL/h", "microliter per hour"},
		{ "um", "micrometer"},
		{ "um/s", "micrometer per second"},
		{ "umol", "micromole"},
		{ "umol/(24.h)", "micromole per 24 hour"},
		{ "umol/d", "micromole per day"},
		{ "umol/dL", "micromole per deciliter"},
		{ "umol/g", "micromole per gram"},
		{ "umol/g{Cre}", "micromole / gram Cre"},
		{ "umol/g{creat}", "micromole per gram of creatinine"},
		{ "umol/g{Hb}", "micromole per gram of hemoglobin"},
		{ "umol/g{hemoglobin}", "micromole per gram of hemoglobin"},
		{ "umol/g{Hgb}", "micromole / gram Hgb"},
		{ "umol/h", "micromole per hour"},
		{ "umol/h/g", "micromole / hour / gram"},
		{ "umol/h/L", "micromole per hour per liter"},
		{ "umol/h/mg{protein}", "micromole per hour per milligram of protein"},
		{ "umol/kg", "micromole per kilogram"},
		{ "umol/L", "micromole per liter"},
		{ "umol/L/h", "micromole per liter per hour"},
		{ "umol/L{rbc}", "micromole per liter of red blood cells"},
		{ "umol/m", "micromole / meter"},
		{ "umol/mg", "micromole per milligram"},
		{ "umol/mg{Cre}", "micromole / milligram Cre"},
		{ "umol/min", "micromole per minute"},
		{ "umol/min/g", "micromole per minute per gram"},
		{ "umol/min/g{prot}", "micromole / minute / gram prot"},
		{ "umol/min/g{protein}", "micromole per minute per gram of protein"},
		{ "umol/min/L", "micromole per minute per liter"},
		{ "umol/mL", "micromole per milliliter"},
		{ "umol/mL/min", "micromole per milliliter per minute"},
		{ "umol/mmol", "micromole per millimole"},
		{ "umol/mol", "micromole per mole"},
		{ "umol/mol{Cre}", "micromole / mole Cre"},
		{ "umol/mol{creat}", "micromole per mole of creatinine"},
		{ "umol/mol{Hb}", "micromole per mole of hemoglobin"},
		{ "umol/umol", "micromole per micromole"},
		{ "uOhm", "microOhm"},
		{ "us", "microsecond"},
		{ "uU", "microUnit"},
		{ "uU/g", "micro enzyme unit per gram"},
		{ "uU/L", "micro enzyme unit per liter"},
		{ "uU/mL", "micro enzyme unit per milliliter"},
		{ "uV", "microvolt"},
		{ "V", "volt"},
		{ "wk", "week"},
		{ "10.uN.s/(cm5.m2)", "10 micronewton second per centimeter to the fifth power per square meter"},
		{ "10*4/uL", "10 thousand per microliter"},
		{ "24.h", "24 hour"},
		{ "A", "Ampère"},
		{ "{ARU}", "aspirin response unit"},
		{ "atm", "standard atmosphere"},
		{ "ag/{cell}", "attogram per cell"},
		{ "Bq", "Becquerel"},
		{ "{binding_index}", "binding index"},
		{ "[bdsk'U]", "Bodansky unit"},
		{ "{CAG_repeats}", "CAG trinucleotide repeats"},
		{ "cal", "calorie"},
		{ "cm[H2O]/s/m", "centimeter of water per second per meter"},
		{ "{delta_OD}", "change in (delta) optical density"},
		{ "{copies}", "copies"},
		{ "{count}", "count"},
		{ "{CPM}", "counts per minute"},
		{ "{CPM}/10*3{cell}", "counts per minute per thousand cells"},
		{ "daL/min", "dekaliter per minute"},
		{ "daL/min/m2", "dekaliter per minute per square meter"},
		{ "{dilution}", "dilution"},
		{ "dyn.s/cm", "dyne second per centimeter"},
		{ "dyn.s/(cm.m2)", "dyne second per centimeter per square meter"},
		{ "{Ehrlich'U}/100.g", "Ehrlich unit per 100 gram"},
		{ "{EIA_index}", "EIA index"},
		{ "{EIA_titer}", "EIA titer"},
		{ "{EV}", "EIA value"},
		{ "U/10", "enzyme unit per 10"},
		{ "U/10*10", "enzyme unit per 10 billion"},
		{ "U/(10.g){feces}", "enzyme unit per 10 gram of feces"},
		{ "U/g{creat}", "enzyme unit per gram of creatinine"},
		{ "U/g{protein}", "enzyme unit per gram of protein"},
		{ "U{25Cel}/L", "enzyme unit per liter at 25 deg Celsius"},
		{ "U{37Cel}/L", "enzyme unit per liter at 37 deg Celsius"},
		{ "U/10*12{RBCs}", "enzyme unit per trillion red blood cells"},
		{ "F", "Farad"},
		{ "fmol/mg{cytosol_protein}", "femtomole per milligram of cytosol protein"},
		{ "fmol/mg{protein}", "femtomole per milligram of protein"},
		{ "{FIU}", "fluorescent intensity unit"},
		{ "{fraction}", "fraction"},
		{ "{GAA_repeats}", "GAA trinucleotide repeats"},
		{ "{genomes}/mL", "genomes per milliliter"},
		{ "{Globules}/[HPF]", "globules (drops) per high power field"},
		{ "g.m/{beat}", "gram meter per heart beat"},
		{ "g{creat}", "gram of creatinine"},
		{ "g{Hb}", "gram of hemoglobin"},
		{ "g{total_nit}", "gram of total nitrogen"},
		{ "g{total_prot}", "gram of total protein"},
		{ "g{wet_tissue}", "gram of wet tissue"},
		{ "g/kg/(8.h)", "gram per kilogram per 8 hour"},
		{ "g/(8.h){shift}", "gram per 8 hour shift"},
		{ "g/cm3", "gram per cubic centimeter"},
		{ "g/g{globulin}", "gram per gram of globulin"},
		{ "g/kg/(8.h){shift}", "gram per kilogram per 8 hour shift"},
		{ "g/kg/h", "gram per kilogram per hour"},
		{ "g/kg/min", "gram per kilogram per minute"},
		{ "g/mol{creat}", "gram per mole of creatinine"},
		{ "g/{specimen}", "gram per specimen"},
		{ "g/{total_output}", "gram per total output"},
		{ "g/{total_weight}", "gram per total weight"},
		{ "Gy", "Gray"},
		{ "{beats}/min", "heart beats per minute"},
		{ "H", "Henry"},
		{ "[HPF]", "high power field"},
		{ "[GPL'U]/mL", "IgG anticardiolipin unit per milliliter**"},
		{ "{GPS'U}", "IgG antiphosphatidylserine unit"},
		{ "[MPL'U]/mL", "IgM anticardiolipin unit per milliliter**"},
		{ "{ISR}", "immune status ratio"},
		{ "{IFA_index}", "immunofluorescence assay index"},
		{ "{IFA_titer}", "Immunofluorescence assay titer"},
		{ "[in_i'H2O]", "inch (international) of water"},
		{ "{index_val}", "index value"},
		{ "{HA_titer}", "influenza hemagglutination titer"},
		{ "[IU]", "international unit"},
		{ "[IU]/L{37Cel}", "international unit per liter at 37 degrees Celsius"},
		{ "[IU]/mg{creat}", "international unit per milligram of creatinine"},
		{ "kat", "katal"},
		{ "kU", "kilo enzyme unit"},
		{ "kU/L{class}", "kilo enzyme unit per liter class"},
		{ "kcal/d", "kilocalorie per day"},
		{ "kcal/kg/(24.h)", "kilocalorie per kilogram per 24 hour"},
		{ "kcal/[oz_av]", "kilocalorie per ounce (US & British)"},
		{ "[ka'U]", "King Armstrong unit"},
		{ "L/(24.h)", "liter per 24 hour"},
		{ "L/s/s2", "liter per second per square second"},
		{ "{Log_copies}/mL", "log (base 10) copies per milliliter"},
		{ "{Log_IU}", "log (base 10) international unit"},
		{ "{Log_IU}/mL", "log (base 10) international unit per milliliter"},
		{ "{Log}", "log base 10"},
		{ "[LPF]", "low power field"},
		{ "lm", "lumen"},
		{ "lm.m2", "lumen square meter"},
		{ "{Lyme_index_value}", "Lyme index value"},
		{ "[mclg'U]", "Mac Lagan unit"},
		{ "Ms", "megasecond"},
		{ "ug/g{feces}", "microgram per gram of feces"},
		{ "ug{FEU}/mL", "microgram fibrinogen equivalent unit per milliliter"},
		{ "ug/(100.g)", "microgram per 100 gram"},
		{ "ug/m3", "microgram per cubic meter"},
		{ "ug/dL{RBCs}", "microgram per deciliter of red blood cells"},
		{ "ug/g{dry_tissue}", "microgram per gram of dry tissue"},
		{ "ug/g{dry_wt}", "microgram per gram of dry weight"},
		{ "ug/g{hair}", "microgram per gram of hair"},
		{ "ug/g{Hb}", "microgram per gram of hemoglobin"},
		{ "ug/g{tissue}", "microgram per gram of tissue"},
		{ "ug/L{RBCs}", "microgram per liter of red blood cells"},
		{ "ug/mL{class}", "microgram per milliliter class"},
		{ "ug/mL{eqv}", "microgram per milliliter equivalent"},
		{ "ug/mmol{creat}", "microgram per millimole of creatinine"},
		{ "ug/{specimen}", "microgram per specimen"},
		{ "ug/[sft_i]", "microgram per square foot (international)"},
		{ "umol{BCE}/mol", "micromole bone collagen equivalent per mole"},
		{ "umol/(2.h)", "micromole per 2 hour"},
		{ "umol/(8.h)", "micromole per 8 hour"},
		{ "umol/dL{GF}", "micromole per deciliter of glomerular filtrate"},
		{ "umol/kg{feces}", "micromole per kilogram of feces"},
		{ "umol/L{RBCs}", "micromole per liter of red blood cells"},
		{ "umol/umol{creat}", "micromole per micromole of creatinine"},
		{ "umol/mg{creat}", "micromole per milligram of creatinine"},
		{ "umol/mmol{creat}", "micromole per millimole of creatinine"},
		{ "umol/min/g{mucosa}", "micromole per minute per gram of mucosa"},
		{ "mU/mmol{creat}", "milli enzyme unit per millimole of creatinine"},
		{ "mU/g{Hb}", "milli enzyme unit per gram of hemoglobin"},
		{ "mU/g{protein}", "milli enzyme unit per gram of protein"},
		{ "mU/mg{creat}", "milli enzyme unit per milligram of creatinine"},
		{ "mbar/L/s", "millibar per liter per second"},
		{ "meq/g{creat}", "milliequivalent per gram of creatinine"},
		{ "meq/{specimen}", "milliequivalent per specimen"},
		{ "meq/{total_volume}", "milliequivalent per total volume"},
		{ "mg{FEU}/L", "milligram fibrinogen equivalent unit per liter"},
		{ "mg/(6.h)", "milligram per 6 hour"},
		{ "mg/{collection}", "milligram per collection"},
		{ "mg/d/{1.73_m2}", "milligram per day per 1.73 square meter"},
		{ "mg/dL{RBCs}", "milligram per deciliter of red blood cells"},
		{ "mg/g{dry_tissue}", "milligram per gram of dry tissue"},
		{ "mg/g{feces}", "milligram per gram of feces"},
		{ "mg/g{tissue}", "milligram per gram of tissue"},
		{ "mg/g{wet_tissue}", "milligram per gram of wet tissue"},
		{ "mg/kg/(8.h)", "milligram per kilogram per 8 hour"},
		{ "mg/kg/h", "milligram per kilogram per hour"},
		{ "mg/L{RBCs}", "milligram per liter of red blood cells"},
		{ "mg/mg{creat}", "milligram per milligram of creatinine"},
		{ "mg/{specimen}", "milligram per specimen"},
		{ "mg/{total_output}", "milligram per total output"},
		{ "mg/{total_volume}", "milligram per total volume"},
		{ "mL{fetal_RBCs}", "milliliter of fetal red blood cells"},
		{ "mL/(5.h)", "milliliter per 5 hour"},
		{ "mL/(6.h)", "milliliter per 6 hour"},
		{ "mL/{beat}", "milliliter per heart beat"},
		{ "mL/{beat}/m2", "milliliter per heart beat per square meter"},
		{ "mmol/(5.h)", "millimole per 5 hour"},
		{ "mmol/{ejaculate}", "millimole per ejaculate"},
		{ "mmol/kg/(8.h)", "millimole per kilogram per 8 hour"},
		{ "mmol/L{RBCs}", "millimole per liter of red blood cells"},
		{ "mmol/mmol{urea}", "millimole per millimole of urea"},
		{ "mmol/mmol{creat}", "millimole per millmole of creatinine"},
		{ "mmol/{specimen}", "millimole per specimen"},
		{ "mmol/{total_vol}", "millimole per total volume"},
		{ "10*6.[CFU]/L", "million colony forming unit per liter"},
		{ "10*6.[IU]", "million international unit"},
		{ "10*6/(24.h)", "million per 24 hour"},
		{ "mPa.s", "millipascal second"},
		{ "{minidrop}/min", "minidrop per minute"},
		{ "{minidrop}/s", "minidrop per second"},
		{ "{molecule}/{platelet}", "molecule per platelet"},
		{ "{mm/dd/yyyy}", "month-day-year"},
		{ "{mutation}", "mutation"},
		{ "nU/mL", "nanoenzyme unit per milliliter"},
		{ "nU/{RBC}", "nanoenzyme unit per red blood cell"},
		{ "ng{FEU}/mL", "nanogram fibrinogen equivalent unit per milliliter"},
		{ "ng/U", "nanogram per enzyme unit"},
		{ "ng/mg{creat}", "nanogram per milligram of creatinine"},
		{ "ng/mg{protein}", "nanogram per milligram of protein"},
		{ "ng/mL{RBCs}", "nanogram per milliliter of red blood cells"},
		{ "ng/10*6{RBCs}", "nanogram per million red blood cells"},
		{ "nmol{BCE}", "nanomole bone collagen equivalent"},
		{ "nmol{BCE}/L", "nanomole bone collagen equivalent per liter"},
		{ "nmol{BCE}/mmol{creat}", "nanomole bone collagen equivalent per millimole of creatinine"},
		{ "nmol{1/2cys}/mg{protein}", "nanomole of 1/2 cystine per milligram of protein"},
		{ "nmol{ATP}", "nanomole of ATP"},
		{ "nmol/dL{GF}", "nanomole per deciliter of glomerular filtrate"},
		{ "nmol/mg{creat}", "nanomole per milligram of creatinine"},
		{ "nmol/mg{protein}", "nanomole per milligram of protein"},
		{ "nmol/mg{protein}/h", "nanomole per milligram of protein per hour"},
		{ "nmol/min", "nanomole per minute"},
		{ "nmol/min/mg{Hb}", "nanomole per minute per milligram of hemoglobin"},
		{ "nmol/min/10*6{cells}", "nanomole per minute per million cells"},
		{ "{#}/[HPF]", "number per high power field"},
		{ "{#}/L", "number per liter"},
		{ "{#}/[LPF]", "number per low power field"},
		{ "{#}/uL", "number per microliter"},
		{ "{#}/mL", "number per milliliter"},
		{ "{#}/min", "number per minute"},
		{ "Ohm.m", "Ohm meter"},
		{ "osm", "osmole"},
		{ "{Pan_Bio'U}", "panbio unit"},
		{ "/10*4{RBCs}", "per 10 thousand red blood cells"},
		{ "/m3", "per cubic meter"},
		{ "/{entity}", "per entity"},
		{ "/g{Hb}", "per gram of hemoglobin"},
		{ "/g{tot_nit}", "per gram of total nitrogen"},
		{ "/g{tot_prot}", "per gram of total protein"},
		{ "/g{wet_tis}", "per gram of wet tissue"},
		{ "/[IU]", "per international unit"},
		{ "/kg{body_wt}", "per kilogram of body weight"},
		{ "/mm", "per millimeter"},
		{ "/mmol{creat}", "per millimole of creatinine"},
		{ "/{OIF}", "per oil immersion field"},
		{ "/nL", "per nanoliter" },
		{ "/10*3", "per thousand"},
		{ "/10*3.{RBCs}", "per thousand red blood cells"},
		{ "/10*12{RBCs}", "per trillion red blood cells"},
		{ "%", "percent" },
		{ "%{loss_AChR}", "percent loss of acetylcholine receptor"},
		{ "%{penetration}", "percent penetration"},
		{ "%{abnormal}", "percent abnormal"},
		{ "%{activity}", "percent activity"},
		{ "%{aggregation}", "percent aggregation"},
		{ "%{at_60_min}", "percent at 60 minute"},
		{ "%{basal_activity}", "percent basal activity"},
		{ "%{binding}", "percent binding"},
		{ "%{blockade}", "percent blockade"},
		{ "%{blocked}", "percent blocked"},
		{ "%{bound}", "percent bound"},
		{ "%{breakdown}", "percent breakdown"},
		{ "%{deficient}", "percent deficient"},
		{ "%{dose}", "percent dose"},
		{ "%{excretion}", "percent excretion"},
		{ "%{Hb}", "percent hemoglobin"},
		{ "%{hemolysis}", "percent hemolysis"},
		{ "%{index}", "percent index"},
		{ "%{inhibition}", "percent inhibition"},
		{ "%{loss}", "percent loss"},
		{ "%{lysis}", "percent lysis"},
		{ "%{normal}", "percent normal"},
		{ "%{normal_pooled_plasma}", "percent normal pooled plasma"},
		{ "%{bacteria}", "percent of bacteria"},
		{ "%{baseline}", "percent of baseline"},
		{ "%{cells}", "percent of cells"},
		{ "%{RBCs}", "percent of red blood cells"},
		{ "%{WBCs}", "percent of white blood cells"},
		{ "%{positive}", "percent positive"},
		{ "%{reactive}", "percent reactive"},
		{ "%{recovery}", "percent recovery"},
		{ "%{reference}", "percent reference"},
		{ "%{residual}", "percent residual"},
		{ "%{saturation}", "percent saturation"},
		{ "%{total}", "percent total"},
		{ "%{uptake}", "percent uptake"},
		{ "%{viable}", "percent viable"},
		{ "{percentile}", "percentile"},
		{ "{phenotype}", "phenotype"},
		{ "pA", "picoampere"},
		{ "pg/{cell}", "picogram per cell"},
		{ "pg/mg{creat}", "picogram per milligram of creatinine"},
		{ "pg/{RBC}", "picogram per red blood cell"},
		{ "pmol/(24.h)", "picomole per 24 hour"},
		{ "pmol/{RBC}", "picomole per red blood cell"},
		{ "[pt_us]", "pint"},
		{ "%{relative}", "relative percent"},
		{ "{relative_saturation}", "relative saturation"},
		{ "{Rubella_virus}", "rubella virus"},
		{ "{saturation}", "saturation"},
		{ "s/{control}", "second per control"},
		{ "S", "Siemens"},
		{ "Sv", "Sievert"},
		{ "{s_co_ratio}", "signal to cutoff ratio"},
		{ "{STDV}", "standard deviation"},
		{ "T", "Tesla"},
		{ "10*3{copies}/mL", "thousand copies per milliliter"},
		{ "10*3{RBCs}", "thousand red blood cells"},
		{ "{TSI_index}", "thyroid-stimulating immunoglobulin index"},
		{ "Wb", "Weber"},
		{ "{WBCs}", "white blood cells"},
		{ "1", "1*"},
		{ "'", "minute"},
		{ "''", "second"},
		{ "%[slope]", "percent of slope"},
		{ "%{Bound}", "PercentBound"},
		{ "/100{Spermatozoa}", "Per100Spermatozoa"},
		{ "/g{HGB}", "PerGramHemoglobin"},
		{ "[acr_br]", "acre"},
		{ "[acr_us]", "acre"},
		{ "[Amb'a'1'U]", "Amb a 1 units"},
		{ "[bbl_us]", "barrel"},
		{ "[bf_i]", "board foot"},
		{ "[Btu]", "British thermal unit"},
		{ "[Btu_39]", "British thermal unit at 39 °F"},
		{ "[Btu_59]", "British thermal unit at 59 °F"},
		{ "[Btu_60]", "British thermal unit at 60 °F"},
		{ "[Btu_IT]", "international table British thermal unit"},
		{ "[Btu_m]", "mean British thermal unit"},
		{ "[Btu_th]", "thermochemical British thermal unit"},
		{ "[bu_br]", "bushel"},
		{ "[bu_us]", "bushel"},
		{ "[c]", "velocity of light"},
		{ "[Cal]", "nutrition label Calories"},
		{ "[car_Au]", "carat of gold alloys"},
		{ "[car_m]", "metric carat"},
		{ "[CCID_50]", "CELL CULTURE INFECTIOUS DOSE 50%"},
		{ "[cft_i]", "cubic foot"},
		{ "[ch_br]", "Gunter's chain"},
		{ "[ch_us]", "Gunter's chain Surveyor's chain"},
		{ "[cicero]", "cicero Didot's pica"},
		{ "[cml_i]", "circular mil"},
		{ "[cr_i]", "cord"},
		{ "[crd_us]", "cord"},
		{ "[cyd_i]", "cubic yard"},
		{ "[D'ag'U]", "D-ANTIGEN UNITS"},
		{ "[didot]", "didot Didot's point"},
		{ "[diop]", "diopter"},
		{ "[dpt_us]", "dry pint"},
		{ "[dqt_us]", "dry quart"},
		{ "[dr_ap]", "dram drachm"},
		{ "[dye'U]", "Dye unit"},
		{ "[e]", "elementary charge"},
		{ "[eps_0]", "permittivity of vacuum"},
		{ "[fdr_br]", "fluid dram"},
		{ "[FFU]", "FOCUS-FORMING UNITS"},
		{ "[ft_br]", "foot"},
		{ "[ft_us]", "foot"},
		{ "[fth_br]", "fathom"},
		{ "[fth_us]", "fathom"},
		{ "[fur_us]", "furlong"},
		{ "[G]", "Newtonian constant of gravitation"},
		{ "[gal_wi]", "historical winchester gallon"},
		{ "[gil_br]", "gill"},
		{ "[gil_us]", "gill"},
		{ "[h]", "Planck constant"},
		{ "[hd_i]", "hand"},
		{ "[hnsf'U]", "Hounsfield unit"},
		{ "[HP]", "horsepower"},
		{ "[hp_C]", "HOMEOPATHIC POTENCY OF CENTESIMAL SERIES"},
		{ "[hp_M]", "HOMEOPATHIC POTENCY OF MILLESIMAL SERIES"},
		{ "[hp_Q]", "HOMEOPATHIC POTENCY OF QUINTAMILLESIMAL SERIES"},
		{ "[hp_X]", "HOMEOPATHIC POTENCY OF DECIMAL SERIES"},
		{ "[in_br]", "inch"},
		{ "[in_i'Hg]", "inch of mercury column"},
		{ "[in_us]", "inch"},
		{ "[iU]/dL", "InternationalUnitsPerDeciLiter"},
		{ "[iU]/g", "InternationalUnitsPerGram"},
		{ "[iU]/kg", "InternationalUnitsPerKilogram"},
		{ "[iU]/L", "InternationalUnitsPerLiter"},
		{ "[iU]/mL", "InternationalUnitsPerMilliLiter"},
		{ "[k]", "Boltzmann constant"},
		{ "[kn_br]", "knot"},
		{ "[kn_i]", "knot"},
		{ "[knk'U]", "Kunkel unit"},
		{ "[lb_ap]", "pound"},
		{ "[lb_tr]", "pound"},
		{ "[lbf_av]", "pound force"},
		{ "[lcwt_av]", "long hunderdweight British hundredweight"},
		{ "[Lf]", "LIMIT OF FLOCCULATION"},
		{ "[ligne]", "ligne French line"},
		{ "[lk_br]", "link for Gunter's chain"},
		{ "[lk_us]", "link for Gunter's chain"},
		{ "[lne]", "line"},
		{ "[lton_av]", "long ton British ton"},
		{ "[ly]", "light-year"},
		{ "[m_e]", "electron mass"},
		{ "[m_p]", "proton mass"},
		{ "[mesh_i]", "mesh"},
		{ "[MET]", "metabolic equivalent"},
		{ "[mi_br]", "mile"},
		{ "[mil_i]", "mil"},
		{ "[mil_us]", "mil"},
		{ "[min_br]", "minim"},
		{ "[mu_0]", "permeability of vacuum"},
		{ "[nmi_br]", "nautical mile"},
		{ "[oz_ap]", "ounce (US and British)"},
		{ "[pc_br]", "pace"},
		{ "[pca]", "pica"},
		{ "[pca_pr]", "Printer's pica"},
		{ "[p'diop]", "prism diopter"},
		{ "[PFU]", "PLAQUE-FORMING UNITS"},
		{ "[pi]", "the number pi"},
		{ "[pied]", "pied French foot"},
		{ "[pk_br]", "peck"},
		{ "[pk_us]", "peck"},
		{ "[pnt]", "point"},
		{ "[pnt_pr]", "Printer's point"},
		{ "[PNU]", "PROTEIN NITROGEN UNITS"},
		{ "[pouce]", "pouce French inch"},
		{ "[PRU]", "peripheral vascular resistance unit"},
		{ "[pwt_tr]", "pennyweight"},
		{ "[rch_us]", "Ramden's chain Engineer's chain"},
		{ "[rd_br]", "rod"},
		{ "[rd_us]", "rod"},
		{ "[rlk_us]", "link for Ramden's chain"},
		{ "[S]", "Svedberg unit"},
		{ "[sc_ap]", "scruple"},
		{ "[sct]", "section"},
		{ "[scwt_av]", "short hundredweight U.S. hundredweight"},
		{ "[smgy'U]", "Somogyi unit"},
		{ "[smi_us]", "square mile"},
		{ "[smoot]", "Smoot"},
		{ "[srd_us]", "square rod"},
		{ "[stone_av]", "stone British stone"},
		{ "[TCID_50]", "TISSUE CULTURE INFECTIOUS DOSE 50%"},
		{ "[twp]", "township"},
		{ "[USP'U]", "UNITED STATES PHARMACOPEIA UNIT"},
		{ "[yd_br]", "yard"},
		{ "[yd_us]", "yard"},
		{ "{Cells}/uL", "CellsPerMicroLiter"},
		{ "{Copies}/mL", "CopiesPerMilliLiter"},
		{ "{Ct}", "crossing threshold"},
		{ "{Ehrlich_U}/dL", "EhrlichUnitsPerDeciLiter"},
		{ "{EhrlichU}/dL", "EhrlichUnitsPerDeciLiter [Arbitrary Concentration Units]"},
		{ "{Elisa_U}/mL", "ElisaUnitsPerMilliLiter"},
		{ "{ElisaU}/mL", "ElisaUnitsPerMilliLiter [Arbitrary Concentration Units]"},
		{ "{kp_C}", "HOMEOPATHIC POTENCY OF CENTESIMAL KORSAKOVIAN SERIES"},
		{ "{rbc}", "red blood cell count"},
		{ "{Spermatozoa}/mL", "SpermatozoaPerMilliLiter"},
		{ "{tbl}", "tablets"},
		{ "{tot}", "particles total count"},
		{ "10*", "the number ten for arbitrary powers"},
		{ "10^", "the number ten for arbitrary powers"},
		{ "a_g", "mean Gregorian year"},
		{ "a_j", "mean Julian year"},
		{ "a_t", "tropical year"},
		{ "Ao", "Ångström"},
		{ "ar", "are"},
		{ "AU", "astronomic unit"},
		{ "b", "barn"},
		{ "B", "bel"},
		{ "B[kW]", "bel kilowatt"},
		{ "B[mV]", "bel millivolt"},
		{ "B[SPL]", "bel sound pressure"},
		{ "B[uV]", "bel microvolt"},
		{ "B[V]", "bel volt"},
		{ "B[W]", "bel watt"},
		{ "Bd", "baud"},
		{ "Bi", "Biot"},
		{ "bit", "bit"},
		{ "bit_s", "bit"},
		{ "By", "byte"},
		{ "C", "Coulomb"},
		{ "cal_[15]", "calorie at 15 °C"},
		{ "cal_[20]", "calorie at 20 °C"},
		{ "cal_IT", "international table calorie"},
		{ "cal_m", "mean calorie"},
		{ "cal_th", "thermochemical calorie"},
		{ "cd", "candela"},
		{ "Ci", "CURIE"},
		{ "circ", "circle"},
		{ "dyn", "dyne"},
		{ "G", "Gauss"},
		{ "g%", "gram percent"},
		{ "g.m/{H.B.}", "gram meter per heartbeat"},
		{ "Gal", "Gal"},
		{ "Gb", "Gilbert"},
		{ "gf", "gram-force"},
		{ "gon", "gon grade"},
		{ "k[iU]/mL", "KiloInternationalUnitsPerMilliLiter"},
		{ "kg{wet'tis}", "kilogram of wet tissue"},
		{ "Ky", "Kayser"},
		{ "Lmb", "Lambert"},
		{ "lx", "lux"},
		{ "m[H2O]", "meter of water column"},
		{ "m[Hg]", "meter of mercury column"},
		{ "mg/{TotalVolume}", "MilliGramPerTotalVolume"},
		{ "mg/mg{Cre}", "MilligramsPerMilligramCreatinine"},
		{ "mg{creat}", "milligram of creatinine"},
		{ "mho", "mho"},
		{ "mmol/{TotalVolume}", "MilliMolesPerTotalVolume [Substance Units]"},
		{ "mmol/mol{Cre}", "MilliMolesPerMoleCreatinine"},
		{ "mo_g", "mean Gregorian month"},
		{ "mo_j", "mean Julian month"},
		{ "mo_s", "synodal month"},
		{ "Mx", "Maxwell"},
		{ "/nL", "per nanoliter" },
		{ "Np", "neper"},
		{ "Oe", "Oersted"},
		{ "P", "Poise"},
		{ "pc", "parsec"},
		{ "ph", "phot"},
		{ "R", "Roentgen"},
		{ "rad", "radian"},
		{ "RAD", "radiation absorbed dose"},
		{ "REM", "radiation equivalent man"},
		{ "sb", "stilb"},
		{ "sph", "spere"},
		{ "sr", "steradian"},
		{ "st", "stere"},
		{ "u", "unified atomic mass unit"},
		{ "uCi", "MICROCURIE"},
		{ "W", "Watt"},
	};
	private static HashMap<String, Pair<String, String>> ucumMap = new LinkedHashMap<>();
	private static HashMap<String, String> commonUcum = new LinkedHashMap<>();
	
	static {
		for (String[] pair: commonUcumUnits) {
			commonUcum.put(pair[0], pair[1]);
		}
		for (String[] pair : mapData) {
			String display = commonUcum.get(pair[1]);
			if (display == null) {
				display = pair[1];
			}
			ucumMap.put(pair[0], Pair.of(pair[1], display));
			// Also put any unit in that is a UCUM unit mapping to itself
			ucumMap.put(pair[1].toUpperCase(), Pair.of(pair[1], display));
		}
	}
	
	private Units() {
	}
	
	/**
	 * Convert a string in ANSI, ISO+ or UCUM units to UCUM
	 * @param unit	The string to convert to a UCUM code
	 * @return	The Coding representing the UCUM unit
	 */
	public static Coding toUcum(String unit) {
		if (unit == null || StringUtils.isBlank(unit)) {
			return null;
		}
		unit = unit.replace("\s+", "");	// Remove any whitespace for lookup
		String display = commonUcum.get(unit);
		if (display != null) {
			return new Coding(Systems.UCUM, unit, display);
		}
		unit = StringUtils.upperCase(unit);  // Convert to Uppercase for lookup
		Pair<String,String> ucumValue = ucumMap.get(unit);
		if (ucumValue == null) {
			return null;
		}
		Coding coding = new Coding(Systems.UCUM, ucumValue.getKey(), ucumValue.getValue());
		// If found in commonUcum, set display name.
		display = commonUcum.get(coding.getCode());
		if (display != null) {
			coding.setDisplay(display);
		}
		return coding;
	}
	
	/**
	 * Check whether a unit string is an actual UCUM code
	 * 
	 * NOTE: UCUM is a code system with a grammar, which means that codes are effectively infinite
	 * in number. This method only checks for UCUM units commonly used in medicine. The lists are extensive,
	 * but it's also possible that some value UCUM codes will be missed by this method.
	 *   
	 * @param unit	A string to check
	 * @return	true if the unit is known to be UCUM, or false otherwise.
	 */
	public static boolean isUcum(String unit) {
		if (StringUtils.isBlank(unit)) {
			return false;
		}
		if (commonUcum.containsKey(unit)) {
			return true;
		}
		Coding coding = toUcum(unit);
		if (coding == null) {
			return false;
		}
		return unit.equals(coding.getCode()); 
	}
}
